# Generated by Django 3.1.7 on 2021-07-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=20)),
                ('symptoms', models.CharField(choices=[('None', 'None'), ('Fever', 'Fever'), ('Cough', 'Cough'), ('Tiredness', 'Tiredness'), ('Aches and pain', 'Aches and Pain'), ('Sore Throat', 'Sore Throat'), ('Diarrhoea', 'Diarrhorea'), ('Loss of taste or smell', 'Loss of taste or smell')], default=None, max_length=25)),
                ('contact_tracing', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('symptoms', models.CharField(default=None, max_length=20)),
                ('contact_tracing', models.IntegerField(default=0)),
                ('probability', models.FloatField(default=0.0)),
                ('stage', models.IntegerField(default=0)),
                ('inf_users_in_dis', models.IntegerField(default=0)),
                ('inf_users_in_state', models.IntegerField(default=0)),
                ('inf_users_in_coun', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='usercreatemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('contact', models.IntegerField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('username', models.CharField(default=None, max_length=20)),
                ('address', models.CharField(default=None, max_length=50)),
                ('district', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('country', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
